defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      section: "Hibi's Retreat"
      icon: "/assets/art/kbwrior.png"
      color: "#808080"
  -
    scope:
      path: "mods"
    values:
      layout: "mod"
      section: "Hibi's Mods"
      color: "#FF00FF"
  -
    scope:
      path: "mod_doc"
    values:
      layout: "mod_doc"
      section: "Hibi's Mods"
      color: "#FF00FF"
