defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      section: "hibi"
      icon: "/assets/art/kbwrior.png"
      color: "#808080"
  -
    scope:
      path: "mods"
    values:
      layout: "mod"
      section: "hibi's mods"
      color: "#FF00FF"
  -
    scope:
      path: "mods/doc"
    values:
      layout: "mod_doc"
      description: "User's Manual and Technical Reference"
      section: "hibi's mods"
      color: "#FF00FF"
